### ISSUE TITLE
Provide attribution to original authors of your Bacula images

### ISSUE THREAD

**Issue by jasperla** [nealef/docker#1]
Hi,

I'm the original author of [redcoolbeans/docker-bacula-opensource](https://github.com/redcoolbeans/docker-bacula-opensource), which you copied almost verbatim into [nealef/docker/bacula](https://github.com/nealef/docker/tree/master/bacula) . I cannot find much original work in here, as even the original `run.sh` scripts were copied.

While you are of course free to use and re-use the files/scripts, providing credit where due, instead of claiming it as your own original work doesn't seem correct.

Edit: feel free to merge these commits
- https://github.com/RedCoolBeans/docker-bacula-opensource/commit/979f580e0f465aefd04cc686c607f3813751d090 
- https://github.com/RedCoolBeans/docker-bacula-opensource/commit/6eea0019572fc3e6b232f6e2e64e4ae2bc6c3555

**Comment by nealef** [comment]
In the github Docker I have attributions. I apologize for not attributing in
the README.md. I will do so immediately and make it obvious where the work
came from. My only excuse was I was trying to get something together for a
demonstration. .

Again, apologies and I will rectify within the hour.

Neale

From:  Jasper Lievisse Adriaanse notifications@github.com
Reply-To:  nealef/docker
<reply++0004b6fa89e1b4edc359ee81e7d118fa0cdde290d91432be92cf0000000112c33b0c9
2a169ce07bc549e@reply.github.com>
Date:  Friday, January 29, 2016 at 9:37 AM
To:  nealef/docker docker@noreply.github.com
Subject:  [docker] Provide attribution to original authors of your Bacula
images (#1)

Hi,

I'm the original author of redcoolbeans/docker-bacula-opensource
https://github.com/redcoolbeans/docker-bacula-opensource , which you
copied almost verbatim into nealef/docker/bacula
https://github.com/nealef/docker/tree/master/bacula  . I cannot find much
original work in here, as even the original run.sh scripts were copied.

While you are of course free to use and re-use the files/scripts, providing
credit where due, instead of claiming it as your own original work doesn't
seem correct.

+IBQ
Reply to this email directly or view it on GitHub
https://github.com/nealef/docker/issues/1 .

**Comment by nealef** [comment]
I have added the following to each of the containers +IBw-Description+IB0 fields:

This work is derived in its entirety on the work of Jasper Lievisse
Adriaanse of The Red Cool Beans project -
(https://www.redcoolbeans.com/contact/) who is the original author and
provides support and development for these containers. I have adapted the
build process and some content for the s390x environment.

Again, I am embarrassed by this oversight. I will go back and check my other
containers. I know that in the Dockerfiles themselves I state where things
come from but if I+IBk-ve missed any I will correct.

Neale

From:  Jasper Lievisse Adriaanse notifications@github.com
Reply-To:  nealef/docker
<reply++0004b6fa89e1b4edc359ee81e7d118fa0cdde290d91432be92cf0000000112c33b0c9
2a169ce07bc549e@reply.github.com>
Date:  Friday, January 29, 2016 at 9:37 AM
To:  nealef/docker docker@noreply.github.com
Subject:  [docker] Provide attribution to original authors of your Bacula
images (#1)

Hi,

I'm the original author of redcoolbeans/docker-bacula-opensource
https://github.com/redcoolbeans/docker-bacula-opensource , which you
copied almost verbatim into nealef/docker/bacula
https://github.com/nealef/docker/tree/master/bacula  . I cannot find much
original work in here, as even the original run.sh scripts were copied.

While you are of course free to use and re-use the files/scripts, providing
credit where due, instead of claiming it as your own original work doesn't
seem correct.

+IBQ
Reply to this email directly or view it on GitHub
https://github.com/nealef/docker/issues/1 .

**Comment by jasperla** [comment]
Thank you, and don't forget to sync this fix: https://github.com/RedCoolBeans/docker-bacula-opensource/commit/ea7f76d960bde3229e8293aac1125f4bc504bf6f :smile:

**Comment by jasperla** [comment]
Also, RedCoolBeans is not a project, but a company. As I mentioned in the edited initial comment of this issue, copyright notices have been added to the run.sh script too to avoid this sort of confusion later on. You might want those two commits too and then close this ticket.

Cheers.

**Comment by nealef** [comment]
Thanks for your understanding. Did you build the bacula RPMs yourself as mine uses /usr rather than /opt. So the one material change I did make was to change those references in the script.

**Comment by nealef** [comment]
I'll add those copyright now.

**Comment by jasperla** [comment]
Yep, we build our own RPMs which use `/opt` to reduce the differences between our commercially available Bacula Enterprise images and these.

**Comment by nealef** [comment]
Understood.

All attribution and copyright added and updated.

**Comment by jasperla** [comment]
Cheers and don't forget to uncomment the `bacula-fd -t` block ;-)
